# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OpenMRAT
                                 A QGIS plugin
 This is an open source implementation of Pedersens equations from 1995
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-12-22
        copyright            : (C) 2022 by Axel Hörteborn
        email                : axel.horteborn@ri.se
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

import os, sys; sys.path.append(os.path.dirname(os.path.realpath(__file__)))
# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OpenMRAT class from file OpenMRAT.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .open_mrat import OpenMRAT
    return OpenMRAT(iface)
