# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OMRATMainWidget
                                 A QGIS plugin
 This is an open source implementation of Pedersens equations from 1995
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-12-22
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Axel Hörteborn
        email                : axel.horteborn@ri.se
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os


from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'omrat_base.ui'))


class OMRATMainWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, plugin=None, parent=None):
        """Constructor."""
        super(OMRATMainWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.plugin = plugin
        self.is_active = True
        
        # Route tab
        self.twRouteList: QtWidgets.QTableWidget
        self.pbAddRoute: QtWidgets.QPushButton
        self.pbLoadRoute: QtWidgets.QPushButton
        self.pbRemoveRoute: QtWidgets.QPushButton
        self.pbStopRoute: QtWidgets.QPushButton
        self.pbUpdateAIS: QtWidgets.QPushButton
        self.laDir1:QtWidgets.QLabel
        self.laDir2:QtWidgets.QLabel
        self.pbStopRoute: QtWidgets.QPushButton
        self.leNormMean1_1: QtWidgets.QLineEdit
        self.leNormMean1_2: QtWidgets.QLineEdit
        self.leNormMean1_3: QtWidgets.QLineEdit
        self.leNormMean2_1: QtWidgets.QLineEdit
        self.leNormMean2_2: QtWidgets.QLineEdit
        self.leNormMean2_3: QtWidgets.QLineEdit
        self.leNormStd1_1: QtWidgets.QLineEdit
        self.leNormStd1_2: QtWidgets.QLineEdit
        self.leNormStd1_3: QtWidgets.QLineEdit
        self.leNormStd2_1: QtWidgets.QLineEdit
        self.leNormStd2_2: QtWidgets.QLineEdit
        self.leNormStd2_3: QtWidgets.QLineEdit
        self.leNormWeight1_1: QtWidgets.QLineEdit
        self.leNormWeight1_2: QtWidgets.QLineEdit
        self.leNormWeight1_3: QtWidgets.QLineEdit
        self.leNormWeight2_1: QtWidgets.QLineEdit
        self.leNormWeight2_2: QtWidgets.QLineEdit
        self.leNormWeight2_3: QtWidgets.QLineEdit
        self.leUniformMin1: QtWidgets.QLineEdit
        self.leUniformMax1: QtWidgets.QLineEdit
        self.leUniformMin2: QtWidgets.QLineEdit
        self.leUniformMax2: QtWidgets.QLineEdit
        self.LEMeanTimeSeconds1: QtWidgets.QLineEdit
        self.LEMeanTimeSeconds2: QtWidgets.QLineEdit
        self.sbUniformP1:QtWidgets.QSpinBox
        self.sbUniformP2:QtWidgets.QSpinBox
        self.DistributionWidget: QtWidgets.QLayout

        #Traffic
        self.cbTrafficSelectSeg: QtWidgets.QComboBox     
        self.cbSelectType: QtWidgets.QComboBox     
        self.cbTrafficDirectionSelect: QtWidgets.QComboBox  
        self.twTrafficData: QtWidgets.QTableWidget   
        
        # Depths
        self.pbAddSimpleDepth: QtWidgets.QPushButton
        self.pbLoadDepth: QtWidgets.QPushButton
        self.pbRemoveDepth: QtWidgets.QPushButton
        self.twDepthList: QtWidgets.QTableWidget
        self.pbGetGebcoDephts: QtWidgets.QPushButton
        self.PBUpdateDepthIntervals: QtWidgets.QPushButton
        self.LEGebcoExtension : QtWidgets.QLineEdit
        self.LEOpenTopoAPIKey: QtWidgets.QLineEdit
        self.LEMaxDepth: QtWidgets.QLineEdit
        self.SBDepthInterval:QtWidgets.QSpinBox
        self.TWDepthIntervals: QtWidgets.QTableWidget
        
        # Objects
        self.twObjectList: QtWidgets.QTableWidget   
        self.pbAddSimpleObject: QtWidgets.QPushButton
        self.pbLoadObject: QtWidgets.QPushButton
        self.pbRemoveObject: QtWidgets.QPushButton
        
        # Run analysis
        self.LEModelName: QtWidgets.QLineEdit
        self.pbRunModel: QtWidgets.QPushButton
        self.TWPreviousRuns: QtWidgets.QTableWidget
        self.pbViewDriftingAllision: QtWidgets.QPushButton
        self.LEPDriftAllision: QtWidgets.QLineEdit
        self.pbViewPoweredAllision: QtWidgets.QPushButton
        self.LEPPoweredAllision: QtWidgets.QLineEdit
        self.pbViewDriftingGrounding: QtWidgets.QPushButton
        self.LEPDriftingGrounding: QtWidgets.QLineEdit
        self.pbViewPoweredGrounding: QtWidgets.QPushButton
        self.LEPPoweredGrounding: QtWidgets.QLineEdit
        self.pbViewOvertakingCollision: QtWidgets.QPushButton
        self.LEPOvertakingCollision: QtWidgets.QLineEdit
        self.pbViewHeadOnCollision: QtWidgets.QPushButton
        self.LEPHeadOnCollision: QtWidgets.QLineEdit
        self.pbViewCrossingCollision: QtWidgets.QPushButton
        self.LEPCrossingCollision: QtWidgets.QLineEdit
        self.pbViewMergingCollision: QtWidgets.QPushButton
        self.LEPMergingCollision: QtWidgets.QLineEdit

        # Analyse drift tab
        self.leDepthThreshold: QtWidgets.QLineEdit
        self.leHeightThreshold: QtWidgets.QLineEdit
        self.pbRunDriftAnalysis: QtWidgets.QPushButton
        self.label_drift_status: QtWidgets.QLabel

    def closeEvent(self, event):
        self.closingPlugin.emit()
        self.plugin.onClosePlugin()
        event.accept()
