# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OMRATMainWidget
                                 A QGIS plugin
 This is an open source implementation of Pedersens equations from 1995
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-12-22
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Axel Hörteborn
        email                : axel.horteborn@ri.se
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'omrat_base.ui'))


class OMRATMainWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(OMRATMainWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.is_active = True
        self.pbAddRoute: QtWidgets.QPushButton
        self.pbLoadRoute: QtWidgets.QPushButton
        self.pbRemoveRoute: QtWidgets.QPushButton
        self.pbStopRoute: QtWidgets.QPushButton
        self.pbUpdateAIS: QtWidgets.QPushButton
        self.pbEditTrafficData: QtWidgets.QPushButton
        self.pbAddSimpleDepth: QtWidgets.QPushButton
        self.pbLoadDepth: QtWidgets.QPushButton
        self.pbRemoveDepth: QtWidgets.QPushButton
        self.pbAddSimpleObject: QtWidgets.QPushButton
        self.pbLoadObject: QtWidgets.QPushButton
        self.pbRemoveObject: QtWidgets.QPushButton
        self.pbRunModel: QtWidgets.QPushButton
        self.cbTrafficSelectSeg: QtWidgets.QComboBox
        self.twRouteList: QtWidgets.QTableWidget
        self.result_layout: QtWidgets.QLayout
        self.result_values:QtWidgets.QLabel
        self.laDir1:QtWidgets.QLabel
        self.laDir2:QtWidgets.QLabel
        self.pbStopRoute: QtWidgets.QPushButton
        self.leNormMean1_1: QtWidgets.QLineEdit
        self.leNormMean1_2: QtWidgets.QLineEdit
        self.leNormMean1_3: QtWidgets.QLineEdit
        self.leNormMean2_1: QtWidgets.QLineEdit
        self.leNormMean2_2: QtWidgets.QLineEdit
        self.leNormMean2_3: QtWidgets.QLineEdit
        self.leNormStd1_1: QtWidgets.QLineEdit
        self.leNormStd1_2: QtWidgets.QLineEdit
        self.leNormStd1_3: QtWidgets.QLineEdit
        self.leNormStd2_1: QtWidgets.QLineEdit
        self.leNormStd2_2: QtWidgets.QLineEdit
        self.leNormStd2_3: QtWidgets.QLineEdit
        self.leNormWeight1_1: QtWidgets.QLineEdit
        self.leNormWeight1_2: QtWidgets.QLineEdit
        self.leNormWeight1_3: QtWidgets.QLineEdit
        self.leNormWeight2_1: QtWidgets.QLineEdit
        self.leNormWeight2_2: QtWidgets.QLineEdit
        self.leNormWeight2_3: QtWidgets.QLineEdit
        self.leUniformMin1: QtWidgets.QLineEdit
        self.leUniformMax1: QtWidgets.QLineEdit
        self.leUniformMin2: QtWidgets.QLineEdit
        self.leUniformMax2: QtWidgets.QLineEdit
        self.LEMeanTimeSeconds1: QtWidgets.QLineEdit
        self.LEMeanTimeSeconds2: QtWidgets.QLineEdit
        self.sbUniformP1:QtWidgets.QSpinBox
        self.sbUniformP2:QtWidgets.QSpinBox
        self.DistributionWidget: QtWidgets.QLayout
        


    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
